//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.A_Rules = new HashSet<A_Rules>();
        }
    
        public int A_id { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string N_N { get; set; }
        public string A_image { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string rule { get; set; }
        public HttpPostedFileBase user_image_data { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Rules> A_Rules { get; set; }
    }
}
