//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Structures
    {
        public int E_S_id { get; set; }
        public bool Type_Q { get; set; }
        public Nullable<int> S_id { get; set; }
        public string def_level { get; set; }
        public int NumofQ { get; set; }
        public Nullable<int> E_id { get; set; }
        public Nullable<int> CH_id { get; set; }
        public bool Post { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual ExamQuestion ExamQuestion { get; set; }
    }
}
