//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Professor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professor()
        {
            this.P_Rules = new HashSet<P_Rules>();
            this.Subjects = new HashSet<Subject>();
        }
    
        public int P_id { get; set; }
        public string name { get; set; }
        public string emai { get; set; }
        public string password { get; set; }
        public string mobile { get; set; }
        public string N_N { get; set; }
        public string rule { get; set; }
        public bool approval { get; set; }
        public string P_image { get; set; }
        public HttpPostedFileBase user_image_data { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Rules> P_Rules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
