//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFquestion
    {
        public int TF_id { get; set; }
        public string content { get; set; }
        public bool correct { get; set; }
        public string def_level { get; set; }
        public int CH_id { get; set; }
        public Nullable<bool> Answer { get; set; }
    
        public virtual Chapter Chapter { get; set; }
    }
}
